//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextLevelLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextLevelLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bip01
        ///bip01 backrightbone
        ///bip01 belly
        ///bip01 c_lowerhead_control
        ///bip01 centerbone
        ///bip01 crown
        ///bip01 crownnub
        ///bip01 footsteps
        ///bip01 front_end
        ///bip01 hatbone
        ///bip01 head
        ///bip01 headnub
        ///bip01 jewel
        ///bip01 jewelnub
        ///bip01 l calf
        ///bip01 l clavicle
        ///bip01 l finger0
        ///bip01 l finger0nub
        ///bip01 l finger21
        ///bip01 l foot
        ///bip01 l forearm
        ///bip01 l hand
        ///bip01 l thigh
        ///bip01 l toe0
        ///bip01 l toe0nub
        ///bip01 l upperarm
        ///bip01 lefteye01
        ///bip01 lower_jaw
        ///bip01 midleftbone
        ///bip01 neck
        ///bip01 neck1
        ///bip01 pelvis
        ///Bip0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoneNames {
            get {
                return ResourceManager.GetString("BoneNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## LM2 ##
        ///
        ///.nlg
        ///00.nlg
        ///02.nlg
        ///03.nlg
        ///04.nlg
        ///05.nlg
        ///06.nlg
        ///06a.nlg
        ///06d.nlg
        ///07.nlg
        ///1
        ///1.nlg
        ///2.nlg
        ///3.nlg
        ///nisasset-art/feghosts/boo.nlg/boo
        ///AnimatedEntity.script
        ///Cameras.script
        ///Hard.script
        ///Easy.script
        ///SuperEasy.script
        ///Medium.script
        ///0.script
        ///1.script
        ///2.script
        ///3.script
        ///Art/Props/CommonAnims/Poltergeist.nlg
        ///Code/Global/Tasks/Flow.script
        ///Art/Props/MansionA/Interactive/Searchable_Wardrobe01/Searchable_Wardrobe_With_Teleport.script
        ///Art/Props/Common_Scripts/HauntedSearchableProp.script
        ///Ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileNames {
            get {
                return ResourceManager.GetString("FileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## LM3 ##
        ///aapostprocess
        ///aopostprocess
        ///atmosphericfog
        ///balloon_scary
        ///base_blended_metal
        ///base_blinking
        ///base_boss_eyes
        ///base_candle
        ///base_crosssection_01
        ///base_emissive
        ///base_emissive_unlit
        ///base_enviroment_cutout
        ///base_environment
        ///base_environment_3tint
        ///base_environment_carpets
        ///base_environment_detailn
        ///base_environment_dusty
        ///base_environment_fogless_01
        ///base_environment_grunge
        ///base_environment_grunge_detailn
        ///base_environment_metalmap_detailn
        ///base_environment_metalmap_wear
        ///base_environment_paint [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaterialNames {
            get {
                return ResourceManager.GetString("MaterialNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attack
        ///background
        ///beetle
        ///blocked
        ///boards
        ///bottle
        ///breaking
        ///bricks
        ///carpers
        ///ceiling
        ///checker
        ///closed
        ///closing
        ///cloth
        ///cobble
        ///collapse
        ///consume
        ///create
        ///curtain
        ///cushion
        ///destroy
        ///detached
        ///door
        ///doorknob
        ///eyes
        ///emitter
        ///exorcising
        ///face
        ///floor
        ///fog
        ///frames
        ///free
        ///fruits
        ///glasses
        ///glow
        ///glowing
        ///goggles
        ///goo
        ///heart
        ///idle
        ///inactive
        ///inset
        ///lamplight
        ///lens
        ///lenses
        ///lid
        ///metal
        ///monitors
        ///off
        ///open
        ///opening
        ///paddle
        ///path
        ///peek
        ///pillow
        ///pipe
        ///plain
        ///planks
        ///plant
        ///portal
        ///possessed
        ///ripped
        ///robomb
        ///rope
        ///sha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global
        ///Global.$lambda0
        ///Global.$lambda1
        ///Global.$lambda2
        ///Global.$lambda3
        ///Global.$lambda4
        ///Global.$lambda5
        ///Global.$lambda6
        ///Global.$lambda7
        ///Global.$lambda8
        ///Global.$lambda9
        ///Global.$lambda10
        ///Global.$lambda11
        ///Global.$lambda12
        ///Global.$lambda13
        ///Global.$lambda14
        ///Global.$lambda15
        ///Global.$lambda16
        ///Global.$lambda17
        ///Global.$lambda18
        ///Global.$lambda19
        ///Global.$lambda20
        ///Global.$lambda21
        ///Global.$lambda22
        ///Global.$lambda23
        ///Global.$lambda24
        ///Global.$lambda25
        ///Global.$lambda26
        ///Global.$lambda27
        ///Global.$la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptStrings {
            get {
                return ResourceManager.GetString("ScriptStrings", resourceCulture);
            }
        }
    }
}
