//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextLevelLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextLevelLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bip01
        ///bip01 backrightbone
        ///bip01 belly
        ///bip01 centerbone
        ///bip01 crown
        ///bip01 crownnub
        ///bip01 footsteps
        ///bip01 front_end
        ///bip01 head
        ///bip01 headnub
        ///bip01 jewel
        ///bip01 jewelnub
        ///bip01 l calf
        ///bip01 l clavicle
        ///bip01 l finger0
        ///bip01 l finger0nub
        ///bip01 l finger21
        ///bip01 l foot
        ///bip01 l forearm
        ///bip01 l hand
        ///bip01 l thigh
        ///bip01 l toe0
        ///bip01 l toe0nub
        ///bip01 l upperarm
        ///bip01 lefteye01
        ///bip01 lower_jaw
        ///bip01 midleftbone
        ///bip01 neck
        ///bip01 neck1
        ///bip01 pelvis
        ///bip01 poltergustbone
        ///bip01 ponytail1
        ///bip01 p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoneNames {
            get {
                return ResourceManager.GetString("BoneNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## LM2 ##
        ///
        ///.nlg
        ///00.nlg
        ///02.nlg
        ///03.nlg
        ///04.nlg
        ///05.nlg
        ///06.nlg
        ///06a.nlg
        ///06d.nlg
        ///07.nlg
        ///1
        ///1.nlg
        ///2.nlg
        ///3.nlg
        ///nisasset-art/feghosts/boo.nlg/boo
        ///AnimatedEntity.script
        ///Cameras.script
        ///Hard.script
        ///Easy.script
        ///SuperEasy.script
        ///Medium.script
        ///0.script
        ///1.script
        ///2.script
        ///3.script
        ///Art/Props/CommonAnims/Poltergeist.nlg
        ///Code/Global/Tasks/Flow.script
        ///Art/Props/MansionA/Interactive/Searchable_Wardrobe01/Searchable_Wardrobe_With_Teleport.script
        ///Art/Props/Common_Scripts/HauntedSearchableProp.script
        ///Ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileNames {
            get {
                return ResourceManager.GetString("FileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAPostProcess
        ///AOPostProcess
        ///AtmosphericFog
        ///Balloon_Scary
        ///Base_Blended_Metal
        ///Base_Blinking
        ///Base_Boss_Eyes
        ///Base_Candle
        ///Base_CrossSection_01
        ///Base_Emissive
        ///Base_Emissive_Unlit
        ///Base_Enviroment_Cutout
        ///Base_Environment
        ///Base_Environment_3Tint
        ///Base_Environment_Carpets
        ///Base_Environment_DetailN
        ///Base_Environment_Dusty
        ///Base_Environment_Fogless_01
        ///Base_Environment_Grunge
        ///Base_Environment_Grunge_DetailN
        ///Base_Environment_MetalMap_DetailN
        ///Base_Environment_MetalMap_Wear
        ///Base_Environment_Paintings
        ///Base_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hashes {
            get {
                return ResourceManager.GetString("Hashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## LM3 ##
        ///aapostprocess
        ///aopostprocess
        ///atmosphericfog
        ///balloon_scary
        ///base_blended_metal
        ///base_blinking
        ///base_boss_eyes
        ///base_candle
        ///base_crosssection_01
        ///base_emissive
        ///base_emissive_unlit
        ///base_enviroment_cutout
        ///base_environment
        ///base_environment_3tint
        ///base_environment_carpets
        ///base_environment_detailn
        ///base_environment_dusty
        ///base_environment_fogless_01
        ///base_environment_grunge
        ///base_environment_grunge_detailn
        ///base_environment_metalmap_detailn
        ///base_environment_metalmap_wear
        ///base_environment_paint [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaterialNames {
            get {
                return ResourceManager.GetString("MaterialNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polterpup
        ///luigicleaner
        ///flashlight
        ///bloo
        ///bloo_gold
        ///bully
        ///chaser
        ///ghost
        ///chaseronline
        ///creeper
        ///gobber
        ///gobber_strong
        ///ghosthider
        ///possessor
        ///poltergeist
        ///poltergeist_strong
        ///sneaker
        ///sister01
        ///sister02
        ///sister03
        ///sister04
        ///bellhop
        ///caveman
        ///headmaid
        ///chef
        ///dj
        ///king
        ///boolossus
        ///boo
        ///cone
        ///leaf
        ///bill
        ///egadd
        ///peach
        ///king/boo
        ///paper
        ///rixer
        ///toad
        ///grump
        ///amysuo
        ///anniee
        ///aouqae
        ///bat
        ///box
        ///fog
        ///goo
        ///lid
        ///off
        ///lit
        ///blue
        ///body
        ///boot
        ///card
        ///crow
        ///dirt
        ///door
        ///eyes
        ///face
        ///free
        ///frog
        ///glow
        ///idle
        ///lens
        ///main
        ///open
        ///p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global
        ///Global.$lambda0
        ///Global.$lambda1
        ///Global.$lambda2
        ///Global.$lambda3
        ///Global.$lambda4
        ///Global.$lambda5
        ///Global.$lambda6
        ///Global.$lambda7
        ///Global.$lambda8
        ///Global.$lambda9
        ///Global.$lambda10
        ///Global.$lambda11
        ///Global.$lambda12
        ///Global.$lambda13
        ///Global.$lambda14
        ///Global.$lambda15
        ///Global.$lambda16
        ///Global.$lambda17
        ///Global.$lambda18
        ///Global.$lambda19
        ///Global.$lambda20
        ///Global.$lambda21
        ///Global.$lambda22
        ///Global.$lambda23
        ///Global.$lambda24
        ///Global.$lambda25
        ///Global.$lambda26
        ///Global.$lambda27
        ///Global.$la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptStrings {
            get {
                return ResourceManager.GetString("ScriptStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///1080
        ///&amp;c
        ///10-point
        ///10th
        ///11-point
        ///12-point
        ///16-point
        ///18-point
        ///1st
        ///2,4,5-t
        ///2,4-d
        ///20-point
        ///2D
        ///2nd
        ///30-30
        ///3D
        ///3-D
        ///3M
        ///3rd
        ///48-point
        ///4-D
        ///4GL
        ///4H
        ///4th
        ///5-point
        ///5-T
        ///5th
        ///6-point
        ///6th
        ///7-point
        ///7th
        ///8-point
        ///8th
        ///9-point
        ///9th
        ///a
        ///a&apos;
        ///a-
        ///A&amp;M
        ///A&amp;P
        ///A.
        ///A.A.A.
        ///A.B.
        ///A.B.A.
        ///A.C.
        ///A.D.
        ///A.D.C.
        ///A.F.
        ///A.F.A.M.
        ///A.G.
        ///A.H.
        ///A.I.
        ///A.I.A.
        ///A.I.D.
        ///A.L.
        ///A.L.P.
        ///A.M.
        ///A.M.A.
        ///A.M.D.G.
        ///A.N.
        ///a.p.
        ///a.r.
        ///A.R.C.S.
        ///A.U.
        ///A.U.C.
        ///A.V.
        ///a.w.
        ///A.W.O.L.
        ///A/C
        ///A/F
        ///A/O
        ///A/P
        ///A/V
        ///A1
        ///A-1
        ///A4
        ///A5
        ///AA
        ///AAA
        ///AAAA
        ///AAAAAA
        ///AAAL
        ///AAAS
        ///Aaberg
        ///Aachen
        ///AAE
        ///AAEE
        ///AAF
        ///AAG
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///AAII
        ///aal
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
